### ISSUE TITLE
Account hash example references nonexistent `easy_client`

### ISSUE THREAD

**Issue by alexgolec** [alexgolec/schwab-py#118]
https://schwab-py.readthedocs.io/en/latest/client.html#account-hashes

**Comment by alexgolec** [comment]
Closing because this method has returned.

**Comment by kowkowhuang** [comment]
Hi @alexgolec — related question:

Yesterday, we attempted to place an option credit spread order via the API, but received a 400 Bad Request error.

The request used the raw account number instead of the hash value:

[2025-05-02 11:02:28 EST.315][_client.py:1025] HTTP Request: POST https://api.schwabapi.com/trader/v1/accounts/38823054/orders "HTTP/1.1 400 Bad Request"  
[2025-05-02 11:02:28 EST.317][tos_client_wrapper.py:129] Not in dry-run mode:place_order:API response: {"message":"Invalid account number"}


Later, I found this in the documentation:
https://schwab-py.readthedocs.io/en/latest/client.html#account-hashes

I’ve now retrieved the account hash.

A couple of questions:

- 1. The hash value appears to be static. Is there a 1:1 mapping between the account number and its hash? Does it ever change (e.g., with token refresh)?

- 2. Should order placement use the hash like this?
https://api.schwabapi.com/trader/v1/accounts/<hash value>/orders

Thanks!


Detailed log below: 


[2025-05-02 11:02:28 EST.043][orb.py:1037] CreditSpread candidates: 
 PUTCS SPXW  250502P05640000(5.3, 5.5)/SPXW  250502P05645000(6.2, 6.3) dte: 0 with $0.85 - 24.1% ITM
[2025-05-02 11:02:28 EST.044][broker_client.py:57] Preparing to sell_to_open with order_template: PUTCS SPXW  250502P05640000(5.3, 5.5)/SPXW  250502P05645000(6.2, 6.3) dte: 0 with $0.85 - 24.1% ITM
[2025-05-02 11:02:28 EST.044][tos_client_wrapper.py:127] Not in dry-run mode, making API call
[2025-05-02 11:02:28 EST.315][_client.py:1025] HTTP Request: POST https://api.schwabapi.com/trader/v1/accounts/38823054/orders "HTTP/1.1 400 Bad Request"
[2025-05-02 11:02:28 EST.317][tos_client_wrapper.py:129] Not in dry-run mode:place_order:API response: {"message":"Invalid account number"}
[2025-05-02 11:02:28 EST.318][engine.py:74] Error while executing due to Client error '400 Bad Request' for url 'https://api.schwabapi.com/trader/v1/accounts/38823054/orders'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400 sleeping 8 seconds
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\engine.py", line 71, in run
    self.execute()
    ~~~~~~~~~~~~^^
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\engine.py", line 102, in execute
    self.orb.sell_to_open_if_possible(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        ignore_trading_window=ignore_trading_window,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        orb_direction_override_for_test=orb_direction,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        dte=dte,
        ^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\strategy\orb.py", line 119, in sell_to_open_if_possible
    self._sell_to_open_if_possible_for_breakout_order(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        breakout_direction=latest_breakout_direction,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        dte=dte,
        ^^^^^^^^
        ignore_trading_window=ignore_trading_window,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\strategy\orb.py", line 169, in _sell_to_open_if_possible_for_breakout_order
    self._sell_to_open_credit_spread(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        credit_spread_to_sell=credit_spread_to_sell,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        credit=credit_spread_to_sell.quote,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\strategy\orb.py", line 948, in _sell_to_open_credit_spread
    broker_order_id = self.broker_client.sell_to_open(
        credit_spread_to_sell=credit_spread_to_sell,
    ...<2 lines>...
        reason=reason,
    )
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\clients\broker_client.py", line 59, in sell_to_open
    order_id = self.broker_client.sell_to_open(
        credit_spread_to_sell=credit_spread_to_sell,
    ...<2 lines>...
        reason=reason,
    )
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\clients\tos.py", line 104, in sell_to_open
    order_id = self.tos_client_wrapper.place_order(order_template)
  File "C:\Users\Lenovo Yoga\Desktop\schwab\SPX0DTE\dte\dte\clients\tos_client_wrapper.py", line 130, in place_order
    res.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Lenovo Yoga\AppData\Local\pypoetry\Cache\virtualenvs\dte-omV90F8f-py3.13\Lib\site-packages\httpx\_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
