### ISSUE TITLE
schwab-py works with docker base ubuntu20 ,not ubuntu22

### ISSUE THREAD

**Issue by fatdrag0n** [alexgolec/schwab-py#184]
## Please read the [bug submission guidelines](https://tda-api.readthedocs.io/en/latest/help.html) before submitting a bug.

Not following guidelines may result in your bug being ignored and/or closed. 

**Description of Bug**
I just dockerized my app after some efforts and it simple is based on schwab-py and basic ubuntu python base os and it install some os apps/pip packages and  It works on ubuntu20 but fails on ubuntu22. Changed underlying host ubuntu to find culprit seems like it is related to the building of image container and some dependencies that fails and cross os version/pip/libaries or something more simpler than that!

**Code to Reproduce**
I run this script where it builds my container and runs it and drop me into bash prompt and I test schwab api!

```docker build -t ubuntu-python .
docker run -it ubuntu-python 
```

```# Use the official Ubuntu base image
FROM ubuntu:20.04
#FROM ubuntu:22.04

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Update package list and install Python, Bash, Git, and Ping utilities
RUN apt-get update && \
    apt-get install -y \
    python3.9 \
    python3.9-distutils \
    python3.9-venv \
    python3-pip \
    bash \
    iputils-ping \
    git \
    curl \
    vim \
    net-tools \
    screen \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3.9 /usr/bin/python
#RUN pip3 install -r requirements.txt
RUN pip3 install python-dateutil
RUN pip3 install httpx
RUN pip3 install requests
RUN pip3 install schwab.py
RUN git clone https://xxxxxxxxxxxxx@github.com/fatdrag0n/marketsignal.git /marketsignal
WORKDIR /marketsignal
COPY token.json schwab/token.json
# Set the default command to bash
CMD ["bash"]
#CMD ["python3"]
```

IMPORTANT: Remember to anonymize your code. Be sure to replace API keys/Client IDs with placeholders. Also, never, ever share the contents of your token file. 

**Expected Behavior**
``` ./chkmktindex.py 
14/11/2024 10:17:41
S&P500: -15.08
DJ: -116.79
Nasdaq: -39.61
Russell2000: -24.83
BTC: -315.0
```

**Actual Behavior**
```root@067b8de62f23:/marketsignal# ./chkmktext.py 
Traceback (most recent call last):
  File "/marketsignal/./chkmktext.py", line 32, in <module>
    from schwab import auth, debug
  File "/usr/local/lib/python3.10/dist-packages/schwab/__init__.py", line 1, in <module>
    from . import auth
  File "/usr/local/lib/python3.10/dist-packages/schwab/auth.py", line 9, in <module>
    import multiprocess
  File "/marketsignal/multiprocess.py", line 30
    def monitor_threads(symbols, time_frames, thread_status, running):
    ^^^
IndentationError: expected an indented block after function definition on line 26

**Error/Exception Log, If Applicable**```
See here to learn how to turn on debug logging: https://tda-api.readthedocs.io/en/latest/help.html```

**Comment by fatdrag0n** [comment]
I like the image just to be able to just install latest python with pip instead of specifying version! I see 3.9..maybe that's the problem!

**Comment by jasonfiammetta** [comment]
That would do it. If you do `pip freeze` I guarantee it'll show the prerelease version of schwab-py, 0.0.0a29.
#176
Might just be best to delete or private those pre-release versions from pypi, a lot of people on the discord have run into this too one way or another

**Comment by fatdrag0n** [comment]
so I fired up ubunrtu22 container again:
saw pip install failed  for few python packages:
``` 
3.08 E: Unable to locate package python3.9-distutils
13.08 E: Couldn't find any package by glob 'python3.9-distutils'
13.08 E: Couldn't find any package by regex 'python3.9-distutils'
13.08 E: Unable to locate package python3.9-venv
13.08 E: Couldn't find any package by glob 'python3.9-venv'
13.08 E: Couldn't find any package by regex 'python3.9-venv'
```
 
and saw pip freeze showing pyschwab version 0.0.0.0a25
I upgraded schwab-py and I see python 3.8 being installed! 

```pip install --upgrade schwab-py
WARNING: The candidate selected for download or install is a yanked version: 'schwab-py' candidate (version 0.0.0a25 at https://files.pythonhosted.org/packages/27/12/5ca0847b8eb2476e510cf6afe56902b6dde5bf4d7f4298098da8b137f209/schwab_py-0.0.0a25-py2.py3-none-any.whl#sha256=99d55e771487f279e556911f974092e280a9fa1ecb4accaf45498d853a9fb6a1 (from https://pypi.org/simple/schwab-py/) (requires-python:>=3.8))
Reason for being yanked: <none given>
Requirement already up-to-date: schwab-py in /usr/local/lib/python3.8/dist-packages (0.0.0a25)
Requirement already satisfied, skipping upgrade: httpx in /usr/local/lib/python3.8/dist-packages (from schwab-py) (0.27.2)
Requirement already satisfied, skipping upgrade: prompt-toolkit in /usr/local/lib/python3.8/dist-packages (from schwab-py) (3.0.48)
Requirement already satisfied, skipping upgrade: authlib in /usr/local/lib/python3.8/dist-packages (from schwab-py) (1.3.2)
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/local/lib/python3.8/dist-packages (from schwab-py) (2.9.0.post0)
Requirement already satisfied, skipping upgrade: websockets in /usr/local/lib/python3.8/dist-packages (from schwab-py) (13.1)
Requirement already satisfied, skipping upgrade: selenium in /usr/local/lib/python3.8/dist-packages (from schwab-py) (4.26.1)
Requirement already satisfied, skipping upgrade: anyio in /usr/local/lib/python3.8/dist-packages (from httpx->schwab-py) (4.5.2)
Requirement already satisfied, skipping upgrade: httpcore==1.* in /usr/local/lib/python3.8/dist-packages (from httpx->schwab-py) (1.0.6)
Requirement already satisfied, skipping upgrade: certifi in /usr/local/lib/python3.8/dist-packages (from httpx->schwab-py) (2024.8.30)
Requirement already satisfied, skipping upgrade: sniffio in /usr/local/lib/python3.8/dist-packages (from httpx->schwab-py) (1.3.1)
Requirement already satisfied, skipping upgrade: idna in /usr/local/lib/python3.8/dist-packages (from httpx->schwab-py) (3.10)
Requirement already satisfied, skipping upgrade: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit->schwab-py) (0.2.13)
Requirement already satisfied, skipping upgrade: cryptography in /usr/local/lib/python3.8/dist-packages (from authlib->schwab-py) (43.0.3)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil->schwab-py) (1.16.0)
Requirement already satisfied, skipping upgrade: typing_extensions~=4.9 in /usr/local/lib/python3.8/dist-packages (from selenium->schwab-py) (4.12.2)
Requirement already satisfied, skipping upgrade: trio~=0.17 in /usr/local/lib/python3.8/dist-packages (from selenium->schwab-py) (0.27.0)
Requirement already satisfied, skipping upgrade: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.8/dist-packages (from selenium->schwab-py) (2.2.3)
Requirement already satisfied, skipping upgrade: trio-websocket~=0.9 in /usr/local/lib/python3.8/dist-packages (from selenium->schwab-py) (0.11.1)
Requirement already satisfied, skipping upgrade: websocket-client~=1.8 in /usr/local/lib/python3.8/dist-packages (from selenium->schwab-py) (1.8.0)
Requirement already satisfied, skipping upgrade: exceptiongroup>=1.0.2; python_version < "3.11" in /usr/local/lib/python3.8/dist-packages (from anyio->httpx->schwab-py) (1.2.2)
Requirement already satisfied, skipping upgrade: h11<0.15,>=0.13 in /usr/local/lib/python3.8/dist-packages (from httpcore==1.*->httpx->schwab-py) (0.14.0)
Requirement already satisfied, skipping upgrade: cffi>=1.12; platform_python_implementation != "PyPy" in /usr/local/lib/python3.8/dist-packages (from cryptography->authlib->schwab-py) (1.17.1)
Requirement already satisfied, skipping upgrade: attrs>=23.2.0 in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium->schwab-py) (24.2.0)
Requirement already satisfied, skipping upgrade: sortedcontainers in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium->schwab-py) (2.4.0)
Requirement already satisfied, skipping upgrade: outcome in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium->schwab-py) (1.3.0.post0)
Requirement already satisfied, skipping upgrade: pysocks!=1.5.7,<2.0,>=1.5.6; extra == "socks" in /usr/local/lib/python3.8/dist-packages (from urllib3[socks]<3,>=1.26->selenium->schwab-py) (1.7.1)
Requirement already satisfied, skipping upgrade: wsproto>=0.14 in /usr/local/lib/python3.8/dist-packages (from trio-websocket~=0.9->selenium->schwab-py) (1.2.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12; platform_python_implementation != "PyPy"->cryptography->authlib->schwab-py) (2.22)
```
then used direction python3.8 call and it worked!
```
/usr/bin/python3.8 ./chkmktindex.py 
17/11/2024 07:26:20
S&P500: 0.0
DJ: 0.0
Nasdaq: 0.0
Russell2000: 0.0
BTC: -87920.0
```
pyschwab needs python3.8 or higher? 3.9 , 3.10 works?

**Comment by fatdrag0n** [comment]
still seeing
schwab-py==0.0.0a25

**Comment by fatdrag0n** [comment]
can't install latest version in the container!?
```
pip uninstall schwab-py
Found existing installation: schwab-py 0.0.0a25
Uninstalling schwab-py-0.0.0a25:
  Would remove:
    /usr/local/lib/python3.8/dist-packages/schwab/*
    /usr/local/lib/python3.8/dist-packages/schwab_py-0.0.0a25.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled schwab-py-0.0.0a25
root@8e7c7b56000f:/marketsignal# pip install schwab-py==1.4  
ERROR: Could not find a version that satisfies the requirement schwab-py==1.4 (from versions: 0.0.0a1, 0.0.0a2, 0.0.0a3, 0.0.0a4, 0.0.0a5, 0.0.0a6, 0.0.0a7, 0.0.0a8, 0.0.0a9, 0.0.0a10, 0.0.0a11, 0.0.0a13, 0.0.0a14, 0.0.0a15, 0.0.0a16, 0.0.0a17, 0.0.0a18, 0.0.0a19, 0.0.0a20, 0.0.0a21, 0.0.0a22, 0.0.0a23, 0.0.0a24, 0.0.0a25)
ERROR: No matching distribution found for schwab-py==1.4
root@8e7c7b56000f:/marketsignal# pip install schwab-py==1.4.0
ERROR: Could not find a version that satisfies the requirement schwab-py==1.4.0 (from versions: 0.0.0a1, 0.0.0a2, 0.0.0a3, 0.0.0a4, 0.0.0a5, 0.0.0a6, 0.0.0a7, 0.0.0a8, 0.0.0a9, 0.0.0a10, 0.0.0a11, 0.0.0a13, 0.0.0a14, 0.0.0a15, 0.0.0a16, 0.0.0a17, 0.0.0a18, 0.0.0a19, 0.0.0a20, 0.0.0a21, 0.0.0a22, 0.0.0a23, 0.0.0a24, 0.0.0a25)
ERROR: No matching distribution found for schwab-py==1.4.0
root@8e7c7b56000f:/marketsignal# pip install schwab-py==1.3.1
ERROR: Could not find a version that satisfies the requirement schwab-py==1.3.1 (from versions: 0.0.0a1, 0.0.0a2, 0.0.0a3, 0.0.0a4, 0.0.0a5, 0.0.0a6, 0.0.0a7, 0.0.0a8, 0.0.0a9, 0.0.0a10, 0.0.0a11, 0.0.0a13, 0.0.0a14, 0.0.0a15, 0.0.0a16, 0.0.0a17, 0.0.0a18, 0.0.0a19, 0.0.0a20, 0.0.0a21, 0.0.0a22, 0.0.0a23, 0.0.0a24, 0.0.0a25)
ERROR: No matching distribution found for schwab-py==1.3.1
```

**Comment by fatdrag0n** [comment]
changed dockerfile to install pyton3.11
now I see schwab-py==1.4.0 installed
but I get error with python3.11 in the container, 
something not right with schwab-py 

I run python3.11 just fine with version 1.2 on a non container standalone ubuntu server

something not right with my container pythong & schwab-py install!
